name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia 'main' con il nome della tua branch principale, se è diversa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build project
      run: |
        # Comandi di build (se non serve build, lascia vuoto)
        # es: npm install && npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Cartella che contiene i file finali
        publish_branch: gh-pages
        force_orphan: true  # Sovrascrive la branch senza cronologia
